English_frequent_words={'and','the', 'of', 'to', 'a', 'in', 'is', 'it', 'you', 'that', 'he', 'was',
'for', 'on', 'are', 'with', 'as', 'I', 'his', 'they', 'be', 'at', 'one', 'have',
'this', 'from', 'or', 'had', 'by', 'hot', 'but', 'some', 'what', 'there', 'we', 'can',
'out', 'other', 'were', 'all', 'your', 'when', 'up', 'use', 'word', 'how', 'said',
'an', 'each', 'she', 'which', 'do', 'their', 'time', 'if', 'will', 'way',
'about', 'many', 'then', 'them', 'would', 'write', 'like', 'so', 'these',
'her', 'long', 'make', 'thing', 'see', 'him', 'two', 'has', 'look', 'more', 'day',
'could', 'go', 'come', 'did', 'my', 'sound', 'no', 'most', 'number', 'who', 'over',
'know',  'than', 'call', 'first', 'people', 'may', 'down', 'side', 'been',
'now', 'find', 'any', 'new', 'part', 'take', 'get', 'made', 'live', 'where',
'after', 'back', 'little', 'only', 'round', 'man', 'year', 'came', 'show', 'every', 'good',
'me', 'give', 'our', 'under', 'name', 'very', 'through', 'just', 'form', 'much', 'great',
'think', 'say', 'help', 'low', 'line', 'before', 'turn', 'cause', 'same', 'mean', 'differ',
'move', 'right', 'boy', 'old', 'too', 'does', 'tell',  'set', 'three', 'want',
'air', 'well', 'also', 'small', 'end', 'put', 'home', 'read', 'hand', 'port', 'large',
'spell', 'add', 'even', 'land', 'here', 'must', 'big', 'high', 'such', 'follow', 'act', 'why',
'ask', 'men', 'change', 'went', 'light', 'kind', 'off', 'need', 'house', 'picture', 'try', 'us',
'again',  'point', 'world', 'near', 'build', 'self', 'earth', 'father',
'head', 'stand', 'own', 'page', 'should', 'country', 'found', 'answer', 'school', 'grow', 'study',
'still', 'learn', 'cover', 'food', 'sun', 'four', 'let', 'keep', 'eye', 'never',
'last', 'between', 'cross', 'since', 'hard', 'start', 'might', 'story',
'saw', 'far',  'draw', 'left', 'late', 'run', 'while', 'press', 'close', 'night',
'real', 'life', 'few', 'stop', 'open', 'seem', 'together', 'next', 'white', 'children', 'begin',
'got', 'walk', 'example', 'ease', 'paper', 'often', 'always', 'music', 'those', 'both', 'mark',
'book', 'letter', 'until', 'mile', 'car', 'feet', 'care', 'second', 'group', 'carry',
'took', 'rain', 'eat', 'room', 'friend', 'began', 'idea', 'fish', 'mountain', 'north', 'once',
'base', 'hear', 'horse', 'cut', 'sure', 'watch', 'color', 'face','main', 'enough', 'plain',
'girl', 'usual', 'young', 'ready', 'above', 'ever', 'red', 'list', 'though', 'feel', 'talk',
'soon', 'dog', 'family', 'direct', 'pose', 'leave', 'song', 'measure', 'state', 'product',
'black', 'short', 'question',
'ship', 'area', 'half', 'rock', 'order', 'fire', 'south', 'problem', 'piece', 'told',
'knew', 'pass', 'farm', 'top', 'whole', 'king', 'size', 'heard', 'best', 'hour', 'better',
'during', 'hundred', 'am', 'remember', 'step', 'early', 'hold',
'reach', 'fast', 'five', 'sing', 'listen', 'six', 'table', 'travel', 'less', 'morning', 'ten',
'simple', 'several', ' toward', 'lay', 'against', 'slow', 'center',
'serve', 'appear', 'road', 'govern', 'pull', 'cold', 'notice', 'voice',
'fall', ' town', 'fine', 'certain', 'fly', 'unit', 'lead', 'cry', 'dark', 'machine', 'note',
'wait', 'plan', 'figure', 'star', 'box', 'noun', 'field', 'rest', 'correct', 'able', 'pound', 'done',
'drive', 'stood', 'contain', 'front', 'teach', 'week', 'final', 'gave', 'green', 'oh', 'quick',
'develop', 'sleep', 'warm', 'free', 'minute', 'strong', 'special',
'behind', 'clear', 'tail', 'produce', 'fact', 'street', 'inch', 'lot',
'nothing', 'course', 'stay', 'wheel', 'full', 'force', 'blue', 'object', 'decide', 'surface',
'deep', 'moon', 'foot', 'yet', 'busy', 'test',
'record', 'boat', 'common', 'gold', 'possible', 'plane', 'age', 'dry', 'wonder',
'laugh', 'thousand', 'ago', 'ran', 'check', 'game', 'shape', 'yes', 'hot', 'miss',
'brought', 'heat', 'snow', 'bed', 'bring',
'sit', 'perhaps', 'fill',  'among'}


